import React, { useCallback, useState } from 'react';
import { FlatList, Pressable, SafeAreaView, StatusBar, StyleSheet, Text, View } from 'react-native';
interface Ong { id: string; name: string; category: string; impact: string; }
const ONGS: Ong[] = [
  { id: '1', name: 'Manos Unidas', category: 'Educación', impact: '320 niños' }, { id: '2', name: 'Huellas de Esperanza', category: 'Animales', impact: '180 rescates' }, { id: '3', name: 'Verde Futuro', category: 'Ambiente', impact: '2.400 árboles' }, { id: '4', name: 'Red de Alimentos', category: 'Ayuda social', impact: '1.200 familias' }, { id: '5', name: 'Puentes de Inclusión', category: 'Inclusión', impact: '90 familias' }, { id: '6', name: 'Casa Abierta', category: 'Salud', impact: '740 consultas' }, { id: '7', name: 'Jóvenes con Futuro', category: 'Empleo', impact: '210 becas' }, { id: '8', name: 'Agua para Todos', category: 'Agua', impact: '18 comunidades' }, { id: '9', name: 'Cultura Viva', category: 'Cultura', impact: '45 talleres' }, { id: '10', name: 'Semillas Rurales', category: 'Ruralidad', impact: '62 productores' }, { id: '11', name: 'Comedores Unidos', category: 'Nutrición', impact: '3.100 raciones' }, { id: '12', name: 'Red de Cuidadores', category: 'Adulto mayor', impact: '130 hogares' },
];
export default function App(): React.JSX.Element {
  const [refreshing, setRefreshing] = useState(false);
  const refresh = useCallback(async () => { setRefreshing(true); await new Promise((resolve) => setTimeout(resolve, 800)); setRefreshing(false); }, []);
  return <SafeAreaView style={styles.safe}><StatusBar barStyle="light-content" backgroundColor="#0d1117" /><FlatList data={ONGS} keyExtractor={(item) => item.id} ListHeaderComponent={<Text style={styles.header}>Organizaciones aliadas</Text>} ItemSeparatorComponent={() => <View style={styles.separator} />} refreshing={refreshing} onRefresh={refresh} renderItem={({ item }) => <Pressable style={({ pressed }) => [styles.item, pressed && styles.pressed]} onPress={() => console.log(item.name)}><View style={styles.info}><Text style={styles.name}>{item.name}</Text><Text style={styles.category}>{item.category}</Text></View><Text style={styles.impact}>{item.impact}</Text></Pressable>} ListEmptyComponent={<Text style={styles.empty}>No hay organizaciones disponibles.</Text>} /></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#0d1117' }, header: { color: '#fff', fontSize: 22, fontWeight: 'bold', padding: 18 }, item: { flexDirection: 'row', alignItems: 'center', padding: 16, backgroundColor: '#161b22' }, pressed: { opacity: 0.65 }, info: { flex: 1 }, name: { color: '#fff', fontSize: 16, fontWeight: '600' }, category: { color: '#8b949e', marginTop: 4 }, impact: { color: '#61DAFB', fontWeight: '600' }, separator: { height: 1, backgroundColor: '#30363d' }, empty: { color: '#8b949e', textAlign: 'center', marginTop: 60 } });
